<a href="https://colab.research.google.com/github/ETorresSacha/clases-MI/blob/main/ejercicios%20sesion%208%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.26.4


3. Create a null vector of size 10 (★☆☆)

In [14]:
vector = np.zeros((10,10))
print(vector)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]



4. How to find the memory size of any array (★☆☆)

In [22]:
vector = np.zeros((10))
memoria = vector.nbytes
print(memoria)
print(vector.itemsize)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
# NOTA: nbytes--> es el producto del peso de cada elemento por la cantidad de elementos.
# calcula el tamoño del array expresados en bytes, pero como el producto final de peso equivalente de cada elemento,
# por el tamaño del array, para el caso de que se trate de un data 34bytes, cada elemento pesará 4bytes mientras que para cada 64 bytes
# cada elemento pesa 8 bytes, depende del sistema operativo que por defecto lo asume.

# itemsize--> solo es el peso de cada elemento de forma independiente

80
8
800 bytes




5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [25]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
x = np.arange(10,51,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


8. Reverse a vector (first element becomes last) (★☆☆)

In [31]:
x = np.arange(10)
x = x[::-1]
print(x)

[9 8 7 6 5 4 3 2 1 0]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:

matriz_random = np.random.rand(3, 2)
print(matriz_random)

Z = np.arange(9).reshape(3, 3)
print(Z)

[[0.23926676 0.63714004]
 [0.15042392 0.14718628]
 [0.72143059 0.74222922]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [42]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)

In [43]:
z = np.eye(4)
print(z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
z = np.random.rand(3,3,3)
print(z)

print("OTRA FORMA")
Z = np.random.random((3,3,3))
print(Z)

matriz_aleatoria = np.random.rand(2, 2)
print(matriz_aleatoria)

[[[0.6145033  0.09175396 0.17458032]
  [0.1574186  0.26812452 0.64738946]
  [0.09814253 0.20393472 0.46532563]]

 [[0.38040615 0.94152577 0.1345695 ]
  [0.72675116 0.46540185 0.26604363]
  [0.540131   0.92414263 0.75705171]]

 [[0.76323518 0.24109589 0.25283841]
  [0.68655875 0.31302692 0.46356384]
  [0.3342678  0.56342874 0.29994071]]]
OTRA FORMA
[[[0.00974028 0.08730028 0.49065588]
  [0.778018   0.44626046 0.01066287]
  [0.0710282  0.25630668 0.31984274]]

 [[0.06828692 0.1914437  0.34144907]
  [0.09568741 0.79465709 0.43624981]
  [0.65435984 0.11087222 0.37218236]]

 [[0.48281772 0.67702035 0.77145301]
  [0.62832368 0.98509468 0.18682371]
  [0.08812657 0.33960508 0.58036392]]]
[[0.40477826 0.82955308]
 [0.2784754  0.68458412]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [56]:
z = np.random.rand(2,2)
print(z)

s = np.random.random((3,3))
print(s)
Zmin, Zmax = Z.min(), Z.max()
#print(Zmin, Zmax)

[[0.61945796 0.92173949]
 [0.75989357 0.81314444]]
[[0.16350707 0.58161138 0.01324283]
 [0.48655913 0.33678218 0.93716152]
 [0.90620169 0.47450121 0.1603408 ]]


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
x = np.random.random(30)
print(x)

y = np.mean(x)
print(y)

[0.89516786 0.71957489 0.5167997  0.99479265 0.93316183 0.4902825
 0.29714788 0.36292259 0.90426695 0.8939605  0.48615388 0.01291571
 0.12248761 0.79133676 0.26014916 0.40967382 0.62346639 0.68979306
 0.45078598 0.26414363 0.71206115 0.11732341 0.76979323 0.08934599
 0.78954236 0.74491334 0.65865673 0.4782985  0.30210352 0.03787632]
0.5272965960319802


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [95]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
# segun entiendo z tiene dos indices, el primero indica las filas y el segundo indica las columnas, ahora el termino 1:-1 significa
# el numero del indice de la matriz, esto quiere decir que comienza en el indice 1 y termina en el ultimo indice, los demas indices se completa con cero.
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [135]:
Z = np.ones((5,5))
# Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
# print(Z)

# Using fancy indexing
# Z[0: -1, :] = 0
Z[[0,-1], :] = 0
Z[:, [0,-1]] = 0 # para este caso se entiende que cuando se coloca [0,-1] se toma de manera particulas los elementos que se encuentran en estos indices, mientras que cuando se coloca 0:-1 se toma como rango

print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
6.2479550353440665
[ 6.24795504  5.24795504  4.24795504  3.24795504  2.24795504  1.24795504
  0.24795504  0.75204496  1.75204496  2.75204496  3.75204496  4.75204496
  5.75204496  6.75204496  7.75204496  8.75204496  9.75204496 10.75204496
 11.75204496 12.75204496 13.75204496 14.75204496 15.75204496 16.75204496
 17.75204496 18.75204496 19.75204496 20.75204496 21.75204496 22.75204496
 23.75204496 24.75204496 25.75204496 26.75204496 27.75204496 28.75204496
 29.75204496 30.75204496 31.75204496 32.75204496 33.75204496 34.75204496
 35.75204496 36.75204496 37.75204496 38.75204496 39.75204496 40.75204496
 41.75204496 42.75204496 43.75204496 44.75204496 45.75204496 46.75204496
 47.75204496 48.75

[-0.22656118  0.13574151]
